### ISSUE TITLE
Can't read property 'honeywell' of undefined

### ISSUE THREAD

**Issue by ArmandoPerdomo** [dorumrr/npmjs-cordova-honeywell-scanner-simplified#6]
i got this exception serving the app with the pluggin

```
rror: Uncaught (in promise): TypeError: Cannot read property 'honeywell' of undefined TypeError: Cannot read property 'honeywell' of undefined at HomePage.webpackJsonp.193.HomePage.listen (http://localhost:8426/build/main.js:81:29) at HomePage.webpackJsonp.193.HomePage.ngOnInit (http://localhost:8426/build/main.js:113:14) at checkAndUpdateDirectiveInline (http://localhost:8426/build/vendor.js:12736:19) at checkAndUpdateNodeInline (http://localhost:8426/build/vendor.js:14260:20) at checkAndUpdateNode (http://localhost:8426/build/vendor.js:14203:16) at debugCheckAndUpdateNode (http://localhost:8426/build/vendor.js:15096:76) at debugCheckDirectivesFn (http://localhost:8426/build/vendor.js:15037:13) at Object.eval [as updateDirectives] (ng:///AppModule/HomePage_Host.ngfactory.js:8:5) at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:8426/build/vendor.js:15022:21) at checkAndUpdateView (http://localhost:8426/build/vendor.js:14169:14) at c (http://localhost:8426/build/polyfills.js:3:19752) at Object.reject (http://localhost:8426/build/polyfills.js:3:19174) at NavControllerBase._fireError (http://localhost:8426/build/vendor.js:51211:16) at NavControllerBase._failed (http://localhost:8426/build/vendor.js:51204:14) at http://localhost:8426/build/vendor.js:51251:59 at t.invoke (http://localhost:8426/build/polyfills.js:3:14976) at Object.onInvoke (http://localhost:8426/build/vendor.js:5085:33) at t.invoke (http://localhost:8426/build/polyfills.js:3:14916) at r.run (http://localhost:8426/build/polyfills.js:3:10143) at http://localhost:8426/build/polyfills.js:3:20242
```

Any help with this?

**Comment by dorumrr** [comment]
Insufficient information to get an idea of what's going on. Most likely you have not defined `window: any = window;`.
